// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/1/2026, 4:26:18 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/Shared/Apps/binarion/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Shared/Apps/binarion/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Shared/Apps/binarion/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Shared/Apps/binarion/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Shared/Apps/binarion/plugins/**/*.{js,ts,mjs}","/Users/Shared/Apps/binarion/composables/**/*.{js,ts,mjs}","/Users/Shared/Apps/binarion/utils/**/*.{js,ts,mjs}","/Users/Shared/Apps/binarion/pages/jobs.vue","/Users/Shared/Apps/binarion/pages/about.vue","/Users/Shared/Apps/binarion/pages/index.vue","/Users/Shared/Apps/binarion/pages/contact.vue","/Users/Shared/Apps/binarion/pages/partner.vue","/Users/Shared/Apps/binarion/pages/job/[id].vue","/Users/Shared/Apps/binarion/pages/impressum.vue","/Users/Shared/Apps/binarion/pages/kandidaten.vue","/Users/Shared/Apps/binarion/pages/datenschutz.vue","/Users/Shared/Apps/binarion/pages/feedback/index.vue","/Users/Shared/Apps/binarion/pages/talente-finden.vue","/Users/Shared/Apps/binarion/pages/talente-finden-backup.vue","/Users/Shared/Apps/binarion/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/Shared/Apps/binarion/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/Shared/Apps/binarion/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;