// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27.10.2025, 10:43:30
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/plugins/**/*.{js,ts,mjs}","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/composables/**/*.{js,ts,mjs}","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/utils/**/*.{js,ts,mjs}","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/pages/jobs.vue","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/pages/index.vue","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/pages/aboutus.vue","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/pages/partner.vue","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/pages/job/[id].vue","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/pages/kandidaten.vue","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/matthiashillebrand/Documents/Homepages/Binarion/binarion/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;