// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 22.4.2025, 17:07:23
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/plugins/**/*.{js,ts,mjs}","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/composables/**/*.{js,ts,mjs}","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/utils/**/*.{js,ts,mjs}","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/pages/blog.vue","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/pages/jobs.vue","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/pages/index.vue","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/pages/kontakt.vue","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/pages/job/[id].vue","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/pages/karriere.vue","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/pages/impressum.vue","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/pages/ueber-uns.vue","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/pages/kandidaten.vue","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/pages/datenschutz.vue","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/pages/unternehmen.vue","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/matthiashillebrand/Documents/Apps/bricks-and-minds/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;